---
version: "3"
services:
 devopsdb:
   image: shaikmustafa/harikanew:dbimage
   ports:
     - "3306:3306"

 application:
   image: shaikmustafa/harikanew:appimage
   ports:
     - "2222:8080"
   depends_on:
     - "devopsdb"
